# Generated by Django 4.0.4 on 2022-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poverty_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre_tc', models.DecimalField(decimal_places=10, max_digits=21)),
                ('gre_rc', models.DecimalField(decimal_places=10, max_digits=21)),
                ('gre_ga', models.DecimalField(decimal_places=10, max_digits=21)),
                ('gce_gdp', models.DecimalField(decimal_places=10, max_digits=21)),
                ('gedo', models.DecimalField(decimal_places=10, max_digits=21)),
                ('sdg', models.DecimalField(decimal_places=10, max_digits=21)),
                ('lg_rex', models.DecimalField(decimal_places=10, max_digits=21)),
                ('lg_cex', models.DecimalField(decimal_places=10, max_digits=21)),
                ('lg_df', models.DecimalField(decimal_places=10, max_digits=21)),
                ('liqratio', models.DecimalField(decimal_places=10, max_digits=21)),
                ('ltdepo', models.DecimalField(decimal_places=10, max_digits=21)),
                ('cbl_ra', models.DecimalField(decimal_places=10, max_digits=21)),
                ('cb_msme', models.DecimalField(decimal_places=10, max_digits=21)),
                ('vt_nse', models.DecimalField(decimal_places=10, max_digits=21)),
            ],
        ),
    ]
