# Generated by Django 4.0.4 on 2022-06-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='poverty_features',
            new_name='PovertyFeatures',
        ),
    ]
