# Generated by Django 4.0.4 on 2022-06-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_poverty_features_povertyfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='povertyfeatures',
            old_name='gre_ga',
            new_name='brent',
        ),
        migrations.RenameField(
            model_name='povertyfeatures',
            old_name='gre_rc',
            new_name='gce_es',
        ),
        migrations.RenameField(
            model_name='povertyfeatures',
            old_name='gre_tc',
            new_name='kero',
        ),
        migrations.RenameField(
            model_name='povertyfeatures',
            old_name='lg_rex',
            new_name='sgd',
        ),
        migrations.RemoveField(
            model_name='povertyfeatures',
            name='sdg',
        ),
    ]
