# Generated by Django 4.0.4 on 2022-06-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_gre_ga_povertyfeatures_brent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='povertyfeatures',
            old_name='cbl_ra',
            new_name='pms',
        ),
    ]
