# Generated by Django 4.0.4 on 2022-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_rename_cbl_ra_povertyfeatures_pms'),
    ]

    operations = [
        migrations.AddField(
            model_name='povertyfeatures',
            name='feature_date',
            field=models.DateField(null=True),
        ),
    ]
