# Generated by Django 4.0.4 on 2022-06-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_povertyfeatures_feature_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProphetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.DateField(null=True)),
                ('yhat', models.DecimalField(decimal_places=10, max_digits=21)),
                ('yhat_lower', models.DecimalField(decimal_places=10, max_digits=21)),
                ('yhat_upper', models.DecimalField(decimal_places=10, max_digits=21)),
            ],
        ),
    ]
