# Generated by Django 4.0.4 on 2022-06-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('prediction_score', models.DecimalField(decimal_places=10, max_digits=21)),
                ('prediction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.predictiontypes')),
            ],
        ),
    ]
