# Generated by Django 4.0.4 on 2022-06-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_predictionhistory_prediction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_date', models.DateTimeField()),
                ('train_score', models.DecimalField(decimal_places=10, max_digits=21)),
                ('train_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.predictiontypes')),
            ],
        ),
    ]
